# Generated by Django 4.1.7 on 2023-03-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='store name')),
                ('address', models.CharField(max_length=200, verbose_name='store address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecommerce_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
